[build]
  command = "parcel build index.html --dist-dir dist --no-content-hash  --public-url ./"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "./icons.*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200