[build]
  command = "parcel build index.html --dist-dir dist --no-content-hash  --public-url ./"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200