[build]
  publish = "dist"
  command = "parcel build index.html --no-content-hash --dist-dir ./dist"
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"